### ISSUE TITLE
Feed cards are now white

### ISSUE THREAD

**Issue by cipri-tom** [StylishThemes/Quora-Dark#13]
It worked great so far ! Could use an update !

Thank you!

![screenshot from 2017-05-20 21 53 15](https://cloud.githubusercontent.com/assets/2991890/26278929/c00b3ae6-3da6-11e7-95b7-67e118822449.png)

**Comment by Mottie** [comment]
Hi @cipri-tom!

Hmm, I'm not seeing the white cards. The style is set up to make them transparent. What class name are you seeing on the cards? This is the HTML structure I'm seeing:

```html
<div class="AnswerFeedStory FeedStory feed_item">
  <div class="StoryItemToggleModal AnswerStoryToggleModal ToggleModal Modal toggle_modal_inline hover_highlight">
    <div class="EventHeader pass_color_to_child_links many_faces ImplicitFollowTopicReason FeedReason">
    ...
    </div>
  </div>
</div>
```

**Comment by cipri-tom** [comment]
All looks fine now. I don't know what happened that day. I'm sorry

**Comment by Mottie** [comment]
I appears that when you log in through a Google account versus logging in directly, different class names are applied to the feed cards. I've updated the userstyle to fix it.

**Comment by cipri-tom** [comment]
ಠ_ಠ mother of bugs! How did you even think of that?

**Comment by Mottie** [comment]
LOL, I didn't... I accidentally created a new account using google authentication <img title=":_nutty:" src="https://cloud.githubusercontent.com/assets/136959/13559403/798d40b4-e3d9-11e5-88b2-df3cbd18c48a.gif">
