### ISSUE TITLE
Bookmarked Questions background not dark

### ISSUE THREAD

**Issue by deep-programmer** [StylishThemes/Quora-Dark#17]
For some of the answers in bookmarked section, background is not dark

![quora_dark__bookmarked_ans](https://user-images.githubusercontent.com/26603964/28315936-39e24476-6bde-11e7-805c-d55a63f35659.png)

Strangely for some others it is dark, as shown in bottom-most question above.

It would be nice to have uniform, dark background for all bookmarked questions.

**Comment by Mottie** [comment]
Hi @deep-programmer!

Thanks for letting us know. All fixed now!

**Comment by deep-programmer** [comment]
Hi @Mottie,

Thanks for making the enhancements !
