### ISSUE TITLE
Preferences overlay background not dark

### ISSUE THREAD

**Issue by deep-programmer** [StylishThemes/Quora-Dark#18]
The semi-transparent background of overlay is white as shown below for preference queries like

What are your interests ?

![quora_dark__interests_overlay_bkgd](https://user-images.githubusercontent.com/26603964/28319623-05afc30a-6bec-11e7-9621-574a2f605d9f.png)

What topics do you know about ?

![quora_dark__what_do_you_know_abt](https://user-images.githubusercontent.com/26603964/28319631-0af09358-6bec-11e7-82c5-5be6ffd101fd.png)

and so on..

It would be great it these are dark as well.

Since this doesn't affect the appearance most of the time, its an optional enhancement

**Comment by Mottie** [comment]
Hi @deep-programmer!

This has been fixed, but I don't plan on updating the style on userstyles.org until I resolve the other two issues.
