### ISSUE TITLE
Background for message box on right not dark

### ISSUE THREAD

**Issue by deep-programmer** [StylishThemes/Quora-Dark#19]
Dark background for following message would be nice

![quora_dark__start_taking_questions](https://user-images.githubusercontent.com/26603964/28320118-63273080-6bed-11e7-914e-bb2b5b4f4898.png)

**Comment by Mottie** [comment]
Hi @deep-programmer!

I am not able to find this exact message panel. Would you please provide the class name of the element with the white background, or a pull request would be awesome!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
