### ISSUE TITLE
Minimized comments are white 

### ISSUE THREAD

**Issue by derekszen** [StylishThemes/Quora-Dark#2]
![capture](https://cloud.githubusercontent.com/assets/9856478/12666633/953555d6-c610-11e5-8649-98d531f73d60.JPG)

Same goes for the current banner on the side. Not sure if this is intentional to give greater visual emphasis.

**Comment by Mottie** [comment]
Hi @Manoflast3!

Thanks for reporting this problem.. it should be all fixed now!
