### ISSUE TITLE
Background for Add topics message is not dark

### ISSUE THREAD

**Issue by deep-programmer** [StylishThemes/Quora-Dark#20]
It would be great to have dark background for messages like these too

![quora_dark__more_qs_to_ans](https://user-images.githubusercontent.com/26603964/28320459-421d176e-6bee-11e7-9afe-806e344de99e.png)

**Comment by Mottie** [comment]
Hi @deep-programmer!

I am not able to find this exact message panel. Would you please provide the class name of the element with the white background, or a pull request would be awesome!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
