### ISSUE TITLE
Stats Background not dark

### ISSUE THREAD

**Issue by deep-programmer** [StylishThemes/Quora-Dark#21]
The background for left pane on [Stats](https://www.quora.com/stats) page is white

![quora_dark__stats](https://user-images.githubusercontent.com/26603964/28322277-52ae38f6-6bf3-11e7-9aaa-58f66542c853.png)

It would be nice it is was dark

**Comment by Mottie** [comment]
Fixed... but the styles may need to be tweaked on the other parts.
