### ISSUE TITLE
Background for Alphabetical Topics on Profile page not dark

### ISSUE THREAD

**Issue by deep-programmer** [StylishThemes/Quora-Dark#22]
On viewing profile page ( www.quora.com/profile/< name > ) , without logging in, the bottom strip beginning with 'Sitemap:' does not have dark background

![quora_dark__topics_alphabetical](https://user-images.githubusercontent.com/26603964/28322669-5596b25e-6bf4-11e7-88fc-40feb7a579c2.png)

It would be nice if its made dark

**Comment by Mottie** [comment]
Hi @deep-programmer!

I am not able to find this exact pager panel. Would you please provide the class name of the element with the white background, or a pull request would be awesome!

**Comment by Mottie** [comment]
Ping @deep-programmer. You have 3 open issues that I can't resolve without more information.
