### ISSUE TITLE
Theme mismatch?

### ISSUE THREAD

**Issue by paulstelian97** [StylishThemes/Quora-Dark#25]
After a potential update of the Quora client code, parts of the website are shown in white, and the text is almost unreadable.
It happens for the specific answer page.

![image](https://user-images.githubusercontent.com/10210293/38636132-12c1ae26-3dd0-11e8-885c-fe37ff53d925.png)

**Comment by paulstelian97** [comment]
The class of the white box div is layout_1col_main_card_inside

**Comment by paulstelian97** [comment]
Adding .layout_1col_main_card on the list for the style {background: transparent !important;} seems to fix it. I have done the fix on my side.

**Comment by Mottie** [comment]
Hi @paulstelian97!

Thanks for the help! I've updated the style.
