### ISSUE TITLE
Add a quora-dark.user.css file

### ISSUE THREAD

**Issue by Apjue** [StylishThemes/Quora-Dark#28]
Stylus doesn't automatically open a new window to install the style when it encounters a css file, it only works with a .user.css

**Comment by the-j0k3r** [comment]
@S6066 

Thank you for your report.

StylishThemes is in the process of dropping support for USo, this means that in a very near future as free time permits, the current css file will be dropped and StylishThemes will only maintain the usercss version.

Im slightly busy atm, but it would take me a few minutes to do this, so expect this done as soon as I have some free time or someone beats me to the punch.

**Comment by the-j0k3r** [comment]
@S6066 

You are welcome to test the usercss style added, it would be appreciated if you provided any feedback in this area.

* Installing UserCSS style
* UserCSS options not working as intended.

**Feel free to add feedback on this ticket.**

Regarding styling: this was just a conversion from normal css to usercss, no styling bug fixes were made.

Note: Any styling bugs you may find should be reported independently (feel free to open another bug report for those), 

Ive noticed one or two on the login page, but I dont use this site, so any of those issues are independent from usercss at this time.

Thank you.

CC: @Mottie

**Comment by Apjue** [comment]
Everything seems to work, I didn't see any bug

**Comment by the-j0k3r** [comment]
Excellent thank you for your feedback, I'll close here for now.
