### ISSUE TITLE
"Top Answers in your Feed" section still bright

### ISSUE THREAD

**Issue by jawshooah** [StylishThemes/Quora-Dark#3]
<img width="350" alt="screen shot 2016-01-29 at 2 36 22 pm" src="https://cloud.githubusercontent.com/assets/4551271/12686084/e311eba4-c695-11e5-9061-4a18fa65e12a.png">

**Comment by Mottie** [comment]
Hi @jawshooah!

Would you share the class name of those elements? I can't seem to find that section.

**Comment by jawshooah** [comment]
Looks like the class is `banner_answer`.

**Comment by Mottie** [comment]
Please check and make sure that fixed the styling :grin:

**Comment by jawshooah** [comment]
It did indeed, thanks!
