### ISSUE TITLE
Shared answers

### ISSUE THREAD

**Issue by maddilasrih** [StylishThemes/Quora-Dark#30]
Hovering around user-shared answers is not supported in this theme. It shows a white selection box around it: 

![screenshot 28](https://user-images.githubusercontent.com/19164585/46090038-7595ad00-c1cd-11e8-963b-5e39f698ff8c.png)

Please fix this in a future update, thank you!

**Comment by Mottie** [comment]
Hi @Harsha2398!

Please share a link to the page in the screenshot, or share the HTML of the unstyled block.

**Comment by the-j0k3r** [comment]
Got, should be a second to push fixes.
