### ISSUE TITLE
Questions and answers are showing with a white backgroud.

### ISSUE THREAD

**Issue by ahartschen** [StylishThemes/Quora-Dark#32]
Here is an example of what I'm talking about. I'm not using any other themes or anything, so I'm not sure what is happening.

![image](https://user-images.githubusercontent.com/16945037/52061733-9d5aa000-2534-11e9-9ff8-fb46d05cc621.png)

**Comment by the-j0k3r** [comment]
Hi and thank you for your report.

Can you post a link to that page please?

**Comment by ahartschen** [comment]
Here is a link: https://www.quora.com/How-do-the-super-rich-handle-their-finances-Does-Bill-Gates-personal-bank-account-actually-say-66-000-000-000-00-available-I-cant-imagine-him-going-down-to-the-local-Chase-Bank-to-withdraw-50-bucks-to-pay-the-cleaner-so-what-happens-instead

It's on any answer page I go to though. Using Firefox and Stylus for the theme.

**Comment by the-j0k3r** [comment]
That link looks like this to me.

![capture](https://user-images.githubusercontent.com/31389848/52064132-3eb51680-2574-11e9-9917-5998aa4cc126.PNG)

Im using Quora Dark 1.3.4 on  Firefox 65.0 and stylus 1.5.2 on Windows 10 with

**Comment by ahartschen** [comment]
I have the exact same setup. I'm not sure what the issue might be then.

**Comment by the-j0k3r** [comment]
What about actual style settings?

![capture](https://user-images.githubusercontent.com/31389848/52065677-52ae4780-2577-11e9-97b5-ecdc08eb2c09.PNG)

**Comment by ahartschen** [comment]
![image](https://user-images.githubusercontent.com/16945037/52066627-8de05480-253e-11e9-9464-030c7e5ee277.png)

**Comment by the-j0k3r** [comment]
Not sure, cant seem to be able to duplicate issue.

**Comment by Mottie** [comment]
https://www.quora.com/How-do-you-draw-a-circle-on-Google-Maps

**Comment by the-j0k3r** [comment]
That page is perfectly fine here... I have some fixes to push in but this is a no dice for me.

**Comment by the-j0k3r** [comment]
Ive pushed some fixes and a release, but I still cant duplicate this issue, so if the many things fixed dont affect this, dont be surprised.
