### ISSUE TITLE
'Related Questions' panel appears white!

### ISSUE THREAD

**Issue by pundoo** [StylishThemes/Quora-Dark#33]
* **Browser**: Chrome 73.0.3683.103 (64-bit)
* **Operating System**: Windows 10 (v1809)
* **Link to page with the issue**: https://www.quora.com/Is-an-electric-toothbrush-better-than-the-manual-one
* **Screenshot**:

![Capture](https://user-images.githubusercontent.com/26104744/56365381-8d3c8d80-6212-11e9-90cc-47598ca8e477.PNG)

**Comment by the-j0k3r** [comment]
Thanks, should be fixed, though cant login so other things have probably broken also.

**Comment by the-j0k3r** [comment]
Its going to be more difficult to style and fix this, they are autogenerating the classes names into some random hash. :/

**Comment by the-j0k3r** [comment]
Ive recently added more fixes related to this (their weird dynamic generated id's/classes), I have a couple of other fixes brewing, but test with latest version 1.3.11 and let me know how it feels and if theres any other issues open a new ticket and report what you notice.

Thanks. =)
