### ISSUE TITLE
Style no longer works properly

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [StylishThemes/Quora-Dark#36]
Hi there the-j0k3r, 
Due to the recent quora changes style no longer works properly on the home page and the menu is too dark to be usable. (pic related)
![Screenshot_2020-01-19 Home - Quora](https://user-images.githubusercontent.com/17363930/72672300-2f1a3080-3a58-11ea-9e39-b3143ca053bf.jpg)

FF 72.0.1 (64-bit) / 1903

**Comment by the-j0k3r** [comment]
@Vulgaris-Viridis please share a link to the offending page, I cant see anything out of the ordinary say at https://www.quora.com/ this is how it looks
![Screenshot_2020-01-19 (1) Home - Quora](https://user-images.githubusercontent.com/31389848/72677967-edae7300-3aa1-11ea-91be-f4c1a8892491.png)

Im on Windows 10 pro 1803 with same Firefox version as you.

**Comment by the-j0k3r** [comment]
@Vulgaris-Viridis I just release v2.0.0[ click here to force upgrade](https://github.com/StylishThemes/Quora-Dark/raw/master/quora-dark.user.css)

I added some fixes and a coulpe of usercss features that arent backwards compatible.

I still cant duplicate your issue, but if when you upgrade, let me know if it fixes the issue you reported or not.

If not please post links to page.

**Comment by Vulgaris-Viridis** [comment]
Hi @the-j0k3r, thanks for your prompt response!

Here's what I'm getting now:
![Screenshot_2020-01-20 Home - Quora-dark](https://user-images.githubusercontent.com/17363930/72691015-3279ee80-3b22-11ea-8001-71f6c36de823.png)

And this is with css disabled:
![Screenshot_2020-01-20 Home - Quora](https://user-images.githubusercontent.com/17363930/72691022-41f93780-3b22-11ea-9834-d30d2a8cfdc6.png)

Exactly identical situation with Chromium v.79.0.3945.88 as well.

**Comment by the-j0k3r** [comment]
@Vulgaris-Viridis please provide a link to that page!

I can tell you that in my setup the menu has no issues in any page nor can I duplicate the lack of post images, but the lack of images on your instance is weird to say the least.

Have you by chance upgraded Windows to 1903 from an earlier version?

:bulb: You may want to reinstall Stylus as well and this style from scratch.

**Comment by Vulgaris-Viridis** [comment]
Hi @the-j0k3r, It's just the homepage, i thought that was clear from the screenshots i posted. 
>Have you by chance upgraded Windows to 1903 from an earlier version?

I didn't but i did install the _"[enablement package](https://www.computerworld.com/article/3455227/microsoft-goes-very-small-for-windows-10-1909s-on-switch.html)"_ update that gives 1909 features to the 1903 version, but i didn't see anything in it that could potentially affect this. I've just reinstalled the Stylus and i got the same results.

**Comment by the-j0k3r** [comment]
> Hi @the-j0k3r, It's just the homepage, i thought that was clear from the screenshots i posted.

Its not immediately obvious because I cant duplicate any of what you see

![Capture](https://user-images.githubusercontent.com/31389848/72709438-41ce5b80-3b65-11ea-9e36-239ae5ff7c1f.PNG)

thats is https://www.quora.com/ right now 9.14AM

>I didn't but i did install the "enablement package" update that gives 1909 features to the 1903 version, but i didn't see anything in it that could potentially affect this. I've just reinstalled the Stylus and i got the same results.

It could be the Upgrade borked something, it wouldn't be the first time I saw all manners of things affected by 1903 upgrades.

This is why I suggested you reinstall Stylus https://github.com/StylishThemes/Quora-Dark#installation and then
Reinstall the style.

Failing that I cant duplicate this at all.

**Comment by Vulgaris-Viridis** [comment]
>Its not immediately obvious because I cant duplicate any of what you see

Well the feed will certainly be different but the page elements themselves can only look like that on the home page, any other tab will have uniquely different elements, is what i meant, but it certainly isn't that important. 

If you can't replicate the issue, then naturally there is little you can do about it, it is probably something on my end, though i tried everything other than fresh FF install, which i might try in the future. 

I will be closing the issue then, no point in keeping it open. Thank you once again for taking time to look into this.

**Comment by the-j0k3r** [comment]
You can try with a fresh Firefox profile. Let me know what happens.

@Mottie for feedback

**Comment by Mottie** [comment]
Feedback

**Comment by the-j0k3r** [comment]
Nice =)

**Comment by Vulgaris-Viridis** [comment]
hi @the-j0k3r / @Mottie  
>You can try with a fresh Firefox profile.

Same. As i mentioned earlier, I'm getting the same results with chromium and no difference when all other extensions are disabled as well. I first suspected that it might be uMatrix/uBlock or another extension that's blocking it but other themes work fine and elements are properly displayed when style is off. 

It is clearly something in this style that's not compatible with my "setup" but at this point it isn't really worth investigating further since i don't use quora lately that often anyways and as i can see you have much more important projects going on there as well. 

If you however choose to investigate it further [_Quora - Dark focused mode_ ](https://userstyles.org/styles/169544/quora-dark-focused-mode) applies the css properly to the _feed_ column on the left but it doesn't style properly other elements, while 
[_Simple Dark Quora_](https://userstyles.org/styles/161127/simple-dark-quoral) is another style that just blocks images. So maybe that offers some clue..

_Quora - Dark focused mode_ 
![Quora - Dark focused mode](https://user-images.githubusercontent.com/17363930/72965830-98ce6d80-3dbd-11ea-94ee-6bf9e7008ab7.jpg)

_Simple Dark Quora_
![Simple Dark Quora](https://user-images.githubusercontent.com/17363930/72965972-f662ba00-3dbd-11ea-92db-558e56bb098b.jpg)




Once again, thanks for your time. Cheers!

**Comment by the-j0k3r** [comment]
Funny.

>Simple Dark Quora is another style that just blocks images

On your screenshots the images are missing, interesting!!

>Quora - Dark focused mode applies the css properly to the feed column on the left but it doesn't style properly other elements

Your screenshots are also showing some elements not styled properly.

>I'm getting the same results with chromium and no difference when all other extensions are disabled as well

This is odd, it could be your other Quora styles are still being loaded somehow and thus causing the breakages you see since all the issues you see are not being duplicated here.
**Make sure you dont have any OPEN styles in Stylus editor when youre testing.**

>I first suspected that it might be uMatrix/uBlock or another extension that's blocking it but other themes work fine and elements are properly displayed when style is off.

This could very well be true in your setup, its not true on mine and without 3rd party confirmation for your issue theres nothing I can do.

What 'Ill do is reopen this issue and put out a req for duplication from anyone else.

**I would suggest you actually remove these other styles and be sure I dont use ublock matrix (I do use origin) and no issues as Ive show on my screenshots.**

I also cant dupe with Firefox, Google Chrome nor Opera in Windows 10 pro 1809 build 17763.973

**Comment by the-j0k3r** [comment]
Ping

**Comment by the-j0k3r** [comment]
@Vulgaris-Viridis ping

Hows this going? Still issues there?

**Comment by Mottie** [comment]
I can confirm that the style is broken. There isn't much we can do about it though... I mean look at the classes we have to work with now

![2020-03-09 07_09_35-DevTools - www quora com_q_weirdwiki](https://user-images.githubusercontent.com/136959/76211858-2aab0200-61d5-11ea-94c2-ca8e3606bb63.png)

Even if we do the work to fix the style, there's no guarantee that the generated class names won't change every time they re-build their stylesheet.

**Comment by the-j0k3r** [comment]
@Mottie Well its broken for two people, you included. It works here.

Buts yes, the dynamic classes suck eggs.

![Screenshot_2020-03-09 General Knowledge - Quora](https://user-images.githubusercontent.com/31389848/76212589-1c76d900-6209-11ea-9b4e-3eaacb8d19ab.jpg)

fixed bg images in https://github.com/StylishThemes/Quora-Dark/commit/f89554b5a2a7ff15c549bc1032f4c69c84ff0ea3

**Comment by the-j0k3r** [comment]
Please try with 2.0.2 tested in Firefox, Goggle Chrome working as above screenshot

**Comment by Vulgaris-Viridis** [comment]
That fixed it for me. Thanks @the-j0k3r. I'll close the issue, if @Mottie still has issues you can reopen it. Cheers! 

![Screenshot_2020-03-09 Home - Quora](https://user-images.githubusercontent.com/17363930/76244383-3d0b5700-623a-11ea-910f-077f78a9bfc8.jpg)
