### ISSUE TITLE
more button issues on comments

### ISSUE THREAD

**Issue by wsor4035** [StylishThemes/Quora-Dark#39]
* **Browser**: Brave
* **Operating System**: Windows
* **Link to page with the issue**: https://qr.ae/pNPYbr
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/24964441/94378348-070ac300-00f7-11eb-9c7d-382b045d0b58.png)

issue: seems to be with nested answers, when you move into the main feed, any more buttons have a white haze around them shown in the screen shot

**Comment by the-j0k3r** [comment]
From issue #40
> 
> 
> * **Browser**: brave
> 
> * **Operating System**: windows
> 
> * **Link to page with the issue**: quora
> 
> * **Screenshot**:
>![image](https://user-images.githubusercontent.com/24964441/94378477-f9097200-00f7-11eb-851e-ae35e7210d04.png)
> 
> 
> issue: the more button seems to be trying to share the same space with text body and while still usable, is mildly annoying

**Comment by the-j0k3r** [comment]
Will push fix some time during the week, its fixed locally,

Bare with me.

**Comment by wsor4035** [comment]
sounds great, thank you, have found a few more issue i need to make actual issue here for, hopefully can do that tonight
