### ISSUE TITLE
Much of the user section has many bright menus/overlays. 

### ISSUE THREAD

**Issue by derekszen** [StylishThemes/Quora-Dark#4]
Here are a couple examples of what I'm talking about. I found them under Profile, blogs, messages, etc. 

![notifications](https://cloud.githubusercontent.com/assets/9856478/12704853/0d8c3f40-c832-11e5-91ab-9a70a920d7d9.JPG)
![what do you know about](https://cloud.githubusercontent.com/assets/9856478/12704858/256ec632-c832-11e5-9249-b116c9031d44.JPG)

I haven't been able to find the class for the first one in particular, and altering .overlay doesn't seem to have any effect on it.

**Comment by Mottie** [comment]
Hi @Manoflast3!

Please try the latest updates... I "think" I fixed these issues, but I was not able to see similar elements. If something is missing, please share a link to the page, or provide a class name for the element. Thanks!

**Comment by derekszen** [comment]
Currently White: 
Underneath stats: .heads_up_item (also have to change the), #__w2_QRqgAax_content_list_wrapper

I have some others but I'm currently busy with work, so I'll see if I can identify them at a later date.

**Comment by Mottie** [comment]
Ok, I added `.heads_up_item`. I would prefer to add a class instead of an ID for the second element, unless it is the ID that is adding the background color.

**Comment by hashhar** [comment]
I think #5 will fix some related stuff. I will try checking out this issue too.

**Comment by Mottie** [comment]
I'm guessing this issue has now been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
