### ISSUE TITLE
another more button issue

### ISSUE THREAD

**Issue by wsor4035** [StylishThemes/Quora-Dark#40]
* **Browser**: brave
* **Operating System**: windows
* **Link to page with the issue**: quora
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/24964441/94378477-f9097200-00f7-11eb-851e-ae35e7210d04.png)

issue: the more button seems to be trying to share the same space with text body and while still usable, is mildly annoying

**Comment by the-j0k3r** [comment]
Theres really no need to open a new ticket for same button. will quote in other ticket.
