### ISSUE TITLE
expanded comment bar after clicking more

### ISSUE THREAD

**Issue by wsor4035** [StylishThemes/Quora-Dark#41]
* **Browser**:  brave
* **Operating System**:  windows
* **Link to page with the issue**: https://www.quora.com/profile/Kevin-Cotter-13
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/24964441/94719131-bd052580-0320-11eb-9c1d-9f55c246c62d.png)

issue: not sure if this is related to issue #39 and #40 when on a users profile, clicking more, and scrolling down to the comments, it juts out a bit more the the answer itself. see screenshot for a example

**Comment by the-j0k3r** [comment]
There is nothing to do here if you use a custom background. Its a side effect of the hack to allow custom backgrounds.

**Comment by the-j0k3r** [comment]
If you wish to not have this issue under background option in stylus choose none;

![Capture](https://user-images.githubusercontent.com/31389848/94890554-d07ad280-047f-11eb-92ca-c99b1bf0d664.PNG)

**Comment by the-j0k3r** [comment]
The background on body now matches this color, so when you select none, you will see the background in a homogeneous color.
