### ISSUE TITLE
spaces on the main tab turn white background when hovered

### ISSUE THREAD

**Issue by wsor4035** [StylishThemes/Quora-Dark#42]
* **Browser**: brave
* **Operating System**: windows
* **Link to page with the issue**: quora
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/24964441/94719379-153c2780-0321-11eb-9a26-0c5ac030d813.png)

issue: on your main quora home page, when hovering over one of your spaces, the background turns white(see image), and doesn't allow you to see the text.

**Comment by the-j0k3r** [comment]
Cant fix this, between the dynamic generated css that will break when quora next updates their site and terrible inline styles I cant find anything that will get to this.

@AfroThundr3007730 @vednoc for ideas?

**Comment by the-j0k3r** [comment]
Theres this too generic selector that seems to work, its not the best way to tackle this though.

```css
  a.q-box.qu-hover--textDecoration--none div:hover {
    color: #333;
  }
  a.q-box.qu-hover--textDecoration--none div div:hover {
    color: #eee;
  }
```

**Comment by the-j0k3r** [comment]
Im adding the so called fix above, further feedback may change that commit, however will leave this open as a reminder to me for now.

**Comment by vednoc** [comment]
Hey @the-j0k3r, I don't use Quora so that menu is unavailable to me. I could have a look if provide me with an example page/snippet.

**Comment by the-j0k3r** [comment]
>, I don't use Quora

Makes two of us, I still wonder how I got dragged into this =)

> I could have a look if provide me with an example page/snippet.

Very kind, thx. Looks like,,, (the whole page)

https://gist.github.com/the-j0k3r/b39ede3c8835eba9b87e18556777e7a0

**Comment by vednoc** [comment]
Seems like they're applying that background via JS because I can't get it to show with hover/active events. I have to assume it's a "good enough" fix for now since this is as far as I can go without making an account.

Have you tried replacing the white background entirely, or are they applying an inline style with `!important` on it?

**Comment by the-j0k3r** [comment]
>Have you tried replacing the white background entirely, or are they applying an inline style with !important on it?

This is not a background color, its a color except the selector it applies to is (from default stylesheet verbatim):
To clarify applying a bg color here does _nada_

```css
.bwxTix:hover {
	color: rgb(228, 230, 230);
}
```
This selector looks dynamic when they regenerate their source, I could be mislead by the name, but they do have many such selectors that have broken in the past. this one being something that use to work and now it broke.

**Comment by vednoc** [comment]
Oh, I see! I was confused because the screenshot had a white background and the linked commit only fixed the text color. 😄

**Comment by the-j0k3r** [comment]
You are confused? Im still wondering why a color property (not background related) afects a background, so yes Im also confused.
