### ISSUE TITLE
shared links turn completely grey when hovered 

### ISSUE THREAD

**Issue by wsor4035** [StylishThemes/Quora-Dark#43]
* **Browser**: brave
* **Operating System**: windows
* **Link to page with the issue**: https://qr.ae/pNPEfh
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/24964441/94719900-c93db280-0321-11eb-82dd-c3214b38100a.png)

issue: may be related to #42 , when hovering over a shared link in a blog, it completely greys out, not allowing you to see anything(see image)

**Comment by the-j0k3r** [comment]
> issue: may be related to #42 , when hovering over a shared link in a blog, it completely greys out, not allowing you to see anything(see image)

unrelated
