### ISSUE TITLE
Somewhere is not fully styled when logging out

### ISSUE THREAD

**Issue by Geeyun-JY3** [StylishThemes/Quora-Dark#44]
Somewhere is not fully styled when logging out. Just see the screenshots below.
* **Browser**: Cent Browser 4.2.10.171 (64-bit) (Chromium 80.0.3987.163)
* **Operating System**: Windows 10 1909
* **Link to page with the issue**: 
  1. Select your language page: https://www.quora.com/about/languages
  2. Login page (after selecting a language which is not corresponding to the region of your IP address?): https://www.quora.com/?prevent_redirect=1
  3. `Login` buttom of the about page: https://www.quora.com/about
* **Screenshot**:
1. Select your language page:
![image](https://user-images.githubusercontent.com/49396421/95600797-36211d00-0a85-11eb-9659-dcf212600872.png)
2. Login page:
![image](https://user-images.githubusercontent.com/49396421/95599769-15a49300-0a84-11eb-9e89-bb4042c3fb0a.gif)
3. `Login` buttom of the about page: 
![image](https://user-images.githubusercontent.com/49396421/95605221-34f2ee80-0a8b-11eb-8f90-03d6a66d1809.png)

**Comment by the-j0k3r** [comment]
Thanks for report.

I can see the bottom issue, but the top looks completely different to me and theres no issues.

![generic](https://user-images.githubusercontent.com/31389848/95610899-5808a880-0a61-11eb-849f-e383d625a5bd.gif)

The bottom screenshot I can see the issue plainly as reported.

Any addition info you can provide to help would be good.

Thx

**Comment by Geeyun-JY3** [comment]
> but the top looks completely different to me and theres no issues.

Have you ever tried to select a language which is different from the region of your IP address? Maybe you can reproduce the Login page issue by doing this (just I think🤣).

**Comment by the-j0k3r** [comment]
> Have you ever tried to select a language which is different from the region of your IP address? Maybe you can reproduce the Login page issue by doing this (just I thinkrofl).

I followed your instructions, my IP is not within an English language region anyway, but I tried several languages in either case.

Perhaps the best thing here is for you to inspect the affected area where you hover the language button and take a screenshot of the inspector showing the affected classes, also a copy of the inner/outer HTML containing the classes would also be helpful together.

Thx

**Comment by Geeyun-JY3** [comment]
I click the `Copy outerHTML` and get this:
```
<div class="language_links u-margin-top--lg"><span class="network_link_arrow"><a class="network_link one-pan-link-mark" href="https://de.quora.com">Deutsch</a><span class="ui_icon ui_icon_color--gray_light ui_icon_size--small ui_icon_outline--default" aria-hidden="true"><svg width="24px" height="24px" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g id="chevron_right" class="icon_svg-stroke" stroke="#666" stroke-width="1.5" fill="none" fill-rule="evenodd" stroke-linecap="round">
        <polyline id="chevron" transform="translate(12.500000, 12.002415) scale(1, -1) rotate(-90.000000) translate(-12.500000, -12.002415) " points="5.49758463 8.50241537 12.4975846 15.5024154 19.5024154 8.50241537"></polyline>
    </g>
</svg></span></span></div>
```
Screenshots:
![image](https://user-images.githubusercontent.com/49396421/95651873-bb591000-0b1f-11eb-8d0a-76e749cea5ec.png)
![image](https://user-images.githubusercontent.com/49396421/95651896-e5aacd80-0b1f-11eb-94c1-cf6bfac0a919.png)

**Comment by the-j0k3r** [comment]
Would you try

```css
.language_links:hover {
  background: #f3f;
}
```

**Comment by Geeyun-JY3** [comment]
> Would you try

How🤣?

**Comment by the-j0k3r** [comment]
Edit the style and put that css in and save

**Comment by Geeyun-JY3** [comment]
![quora](https://user-images.githubusercontent.com/49396421/98362404-20911a00-2068-11eb-9910-01bb699b9ac8.gif)

**Comment by Geeyun-JY3** [comment]
OK now it is the same.

**Comment by the-j0k3r** [comment]
works fine here
