### ISSUE TITLE
Theme template?

### ISSUE THREAD

**Issue by nathgit** [StylishThemes/Quora-Dark#45]
### I would like to be able do the following

1. Is there a template somewhere for how to create custom themes like this one?
2.
3.

### Additional context

 I know how to user the "root:" / variables themselves, but not how to create the custom popup in the Stylus dropdown.

**Comment by the-j0k3r** [comment]
If you study the https://github.com/StylishThemes/Quora-Dark/blob/master/quora-dark.user.css you will see it

UserCSS meta, needed

https://github.com/StylishThemes/Quora-Dark/blob/2ad814b8670eece135f42e694017e5f809b3a64f/quora-dark.user.css#L2-L8

https://github.com/StylishThemes/Quora-Dark/blob/2ad814b8670eece135f42e694017e5f809b3a64f/quora-dark.user.css#L9-L46

https://github.com/StylishThemes/Quora-Dark/blob/2ad814b8670eece135f42e694017e5f809b3a64f/quora-dark.user.css#L47

Specifically , the parts between `/* ==UserStyle==  ==/UserStyle== */` like above

Theres many ways  to add options. Stylus wiki has more info about preprocessors to use.  https://github.com/openstyles/stylus/wiki/UserCSS and https://github.com/openstyles/stylus/wiki/Writing-UserCSS and other pgaes.
