### ISSUE TITLE
Mouse enter produces light highlight

### ISSUE THREAD

**Issue by cipri-tom** [StylishThemes/Quora-Dark#7]
![quora](https://cloud.githubusercontent.com/assets/2991890/17792369/9cefa116-65a0-11e6-9085-ac9a12cad5ea.gif)

And I believe this is the troublesome element:
![screenshot from 2016-08-19 00 10 25](https://cloud.githubusercontent.com/assets/2991890/17792518/62f554be-65a1-11e6-93f3-815199175898.png)
`
<div class="QuestionStoryToggleModal StoryItemToggleModal ToggleModal Modal FeedQuestionStoryToggleModal toggle_modal_inline hover_highlight" id="__w2_QV8sEUz__inline">...</div>`

**Comment by Mottie** [comment]
Hi @cipri-tom!

Thanks for sharing the class names, it really helped!
