### ISSUE TITLE
Search suggestions are white

### ISSUE THREAD

**Issue by cipri-tom** [StylishThemes/Quora-Dark#8]
I'm sorry I don't know any CSS to fix these myself ... 

![screenshot from 2016-08-20 00 06 16](https://cloud.githubusercontent.com/assets/2991890/17825785/1f847a1e-666b-11e6-88e8-160151551982.png)

And the div is one of these. Can't pin-point exactly which one:
![screenshot from 2016-08-20 00 09 35](https://cloud.githubusercontent.com/assets/2991890/17825815/4a56b5c2-666b-11e6-9bdc-4d615c9c0348.png)

**Comment by Mottie** [comment]
Hi @cipri-tom!

I'll look at it now :grin:
