### ISSUE TITLE
white color clicking  in (more) link

### ISSUE THREAD

**Issue by diegogslomp** [StylishThemes/Quora-Dark#9]
Hi!
I fixed this adding to a custom style:

`@-moz-document domain("www.quora.com") {
.Modal .modal_header, .Modal .modal_content .modal_non_exp, .Modal .modal_content {
	background-color: transparent;
}}`

Before the fix:
![before](https://cloud.githubusercontent.com/assets/3443988/22247253/04c80b60-e220-11e6-8a1d-b066a21f2c84.png)
After:
![after](https://cloud.githubusercontent.com/assets/3443988/22247269/141d2014-e220-11e6-99f6-641222a2aeb2.png)

**Comment by Mottie** [comment]
Hi @diegogslomp!

Thanks for letting us know! It's been all fixed!
